import { describe, it, expect } from "vitest";
import { existsSync } from "node:fs";
import { decodePng, faceTone, transparentShare } from "../helpers/png.js";

/**
 * The Explorer ships as five PNGs, one per onboarding skin tone. That set is the game's
 * representation promise, and it is regenerated by hand in an image tool — so the failure
 * modes are silent and real:
 *
 *  - a regenerated file lands on the wrong tone and the ordering breaks, so the tone a child
 *    picked isn't the child they see;
 *  - the set drifts light, leaving the deep end unrepresented (the whole point of five);
 *  - an export loses its alpha and ships an opaque box over the background (already caught
 *    once on the deer).
 *
 * These are cheap to check and invisible until a child plays, so they're pinned here.
 * Keep in sync with AVATAR_FILES in src/content/assetManifest.ts.
 */

const AVATARS: Array<{ tone: string; file: string }> = [
  { tone: "tone_1", file: "nova-light-fair.png" },
  { tone: "tone_2", file: "nova-light-tan.png" },
  { tone: "tone_3", file: "nova-warm-medium.png" },
  { tone: "tone_4", file: "nova-warm-medium-brown.png" },
  { tone: "tone_5", file: "nova-deep-brown.png" },
];

const dir = "public/assets/characters/";
const measured = AVATARS.map(({ tone, file }) => {
  const png = decodePng(dir + file);
  return { tone, file, png, tone_: faceTone(png) };
});

describe("avatar art — five tones that stay five distinct tones", () => {
  it("has a file for every onboarding tone", () => {
    for (const { file } of AVATARS) {
      expect(existsSync(dir + file), `${file} is missing`).toBe(true);
    }
  });

  it("is a genuine cutout, not an opaque box over the background", () => {
    for (const { file, png } of measured) {
      expect(transparentShare(png), `${file} has almost no transparency`).toBeGreaterThan(0.15);
    }
  });

  it("darkens monotonically from tone_1 to tone_5", () => {
    for (let i = 1; i < measured.length; i++) {
      const prev = measured[i - 1];
      const cur = measured[i];
      expect(
        cur.tone_.luminance,
        `${cur.file} (${cur.tone}) is not darker than ${prev.file} (${prev.tone}) — ` +
          `the tone a child picks would not match the child they see`,
      ).toBeLessThan(prev.tone_.luminance);
    }
  });

  it("keeps the tones far enough apart to read as different children", () => {
    for (let i = 1; i < measured.length; i++) {
      const gap = measured[i - 1].tone_.luminance - measured[i].tone_.luminance;
      expect(
        gap,
        `${measured[i].file} is only ${gap.toFixed(0)} luminance from the previous tone`,
      ).toBeGreaterThan(10);
    }
  });

  it("actually covers a broad range, so the deep end is represented", () => {
    const lightest = measured[0].tone_.luminance;
    const darkest = measured[measured.length - 1].tone_.luminance;
    expect(lightest, "the lightest tone is not light enough").toBeGreaterThan(180);
    // The intended tone_5 (#4a2c14) sits near 45. The current set stops at ~100, so this
    // holds the line at today's value and fails if a regeneration drifts even lighter.
    expect(
      darkest,
      "the darkest tone has drifted lighter — the deep end is losing representation",
    ).toBeLessThanOrEqual(105);
  });
});
